version: "3.8"

services:
  backend:
    build:
      context: ./backend           
      dockerfile: Dockerfile    
    ports:
      - "8080:8080"
    env_file:
      - .env
    # volumes:
    #   - ./backend:/app
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data        
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      - ./init_data_uuid.js:/docker-entrypoint-initdb.d/init_data_uuid.js:ro

volumes:
  pgdata:
  mongo_data:

networks:
  backend:
