
version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data        
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d school_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongodb/init_data_uuid.js:/docker-entrypoint-initdb.d/init_data_uuid.js:ro
    networks:
      - backend

volumes:
  pgdata:
  mongo_data:

networks:
  backend:

